version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
  - package_manager: "dotnet:nuget"
    directory: "/tests/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  - package_manager: "dotnet:nuget"
    directory: "/targets"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
